apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::538610996748:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::538610996748:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-12UW5GJV92030
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:masters\n  rolearn: arn:aws:iam::538610996748:role/UdacityFlaskDeployCBKubectlRole\n  username: build \n- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::538610996748:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-12UW5GJV92030\n  username: system:node:{{EC2PrivateDNSName}}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2021-08-22T01:35:08Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1208","uid":"b429bec7-3bd8-4cc5-9d87-57726aff2583"}}
  creationTimestamp: 2021-09-01T12:34:30Z
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: 2021-09-01T12:34:30Z
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
        f:mapUsers: {}
    manager: kubectl-patch
    operation: Update
    time: 2021-09-01T13:50:03Z
  name: aws-auth
  namespace: kube-system
  resourceVersion: "17240"
  uid: 908cd147-8f8f-46f7-a80d-f3f37cd4e205
