apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::245580300024:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-14GNK8BW0YPUY
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-22T01:58:17Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1359"
  uid: 6e99c0c6-fd4a-4759-a488-1861186f59e3
