apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::899385446384:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::899385446384:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-33G3NZU51DEU
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-03T17:50:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1191"
  uid: afdf9896-74c3-4612-a483-66cb48d867e5
